# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a75da8fd9d6cc2315190d75a3e0faee8ec73afb107af6bf72221167f103008350e82a4541aea8e01b0e7b85992551210257cafd493f4504a399dd4831fc53b42

test:
  secret_key_base: aadf7254b7a256ff6537e9238938727f2bad884ba44e461099a395c7c7fc01113096eefed0b993d74b22c507963348142f413f0c502e472bfc8973c7f9128194

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
